# Generated by Django 2.0.7 on 2018-07-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='author',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='books_catalog.Author'),
        ),
    ]
