# Generated by Django 2.0.7 on 2018-08-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_catalog', '0003_auto_20180730_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(help_text='Enter an author biography'),
        ),
    ]
